spring:
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@10.5.192.49:1521/ORCL
      url: jdbc:oracle:thin:@localhost:1521:ORCL
      username: root
      password: YSWRoot

      #指定初始化数据源，是否用data.sql来初始化，默认: true
#      initialize: false
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        #配置初始化大小、最小、最大
        initialSize: 1
        minIdle: 3
        maxActive: 20

        #配置获取连接等待超时的时间
        maxWait: 60000

        #有两个含义：1) Destroy线程会检测连接的间隔时间
        #           2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
        timeBetweenEvictionRunsMillis: 60000

        #配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000

        #物理连接初始化的时候执行的sql
        #connectionInitSqls: sql

        #当数据库抛出一些不可恢复的异常时，抛弃连接
        #exceptionSorter: null

        #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
        #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        testWhileIdle: true

        #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        testOnBorrow: false
        #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        testOnReturn: false

        #用来检测连接是否有效的sql，要求是一个查询语句。
        #如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
        validationQuery: SELECT 'x' from dual

        #是否缓存preparedStatement，也就是PSCache。
        #PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
        poolPreparedStatements: true

        #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
        #在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
        maxPoolPreparedStatementPerConnectionSize: 100

        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        #useGlobalDataSourceStat: true

        #打开removeAbandoned功能
        removeAbandoned: true

        #1800秒，也就是30分钟
        removeAbandonedTimeout: 1800

        #关闭abanded连接时输出错误日志
        logAbandoned: true